### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by prajaybasu** [BioTurboNick/Skryptonite#1]
Hello, I am thankful for the library, I would just like to confirm that this library, from what I can understand is licensed under a simpler, classier version of GNU GPL v2 ?

**Comment by BioTurboNick** [comment]
Thanks for the compliment, glad someone is interested. As I understand it, mostly yes. I'm still fairly new to the licensing game. I think the main difference is that I don't want to require that the products the code is used in to be open-sourced too, it's only the "modifications" that would have to be open-sourced by virtue of being offered back to the project.

**Comment by prajaybasu** [comment]
I suppose you are looking for a license like LGPL.

**Comment by BioTurboNick** [comment]
I think you're right, that looks like a suitable license. I'll adopt LGPL 3.0. Thanks!
