### ISSUE TITLE
CoreCLR implementation ?

### ISSUE THREAD

**Issue by prajaybasu** [BioTurboNick/Skryptonite#2]
Hello, 
I landed up on your SO question sometime ago and would like to know, do you still have the CoreCLR implementation (i.e System.Numerics) instead of .NET Native ?

**Comment by BioTurboNick** [comment]
I'm not sure if I understand. Are you asking whether I have a version using System.Numerics? If so, I do not. I abandoned it when I realized I couldn't get it performing efficiently. Why do you ask?

**Comment by prajaybasu** [comment]
I suppose System.Numerics would work as intended on platforms other than UWP (.NET Native) like CoreCLR( which would be cross platform for the most), but thanks for replying anyway.

**Comment by BioTurboNick** [comment]
There are several other existing libraries available via Nuget that appear to work with .Net more generally, though I haven't tested them or looked deeply into them. I might reconsider if/when .Net Native does support System.Numerics.
